### ISSUE TITLE
Не ясен полный функционал из описания.

### ISSUE THREAD

**Issue by huxuxuya** [ZhukovGreen/gcal_time_track_tg_bot#1]
Полностью не понятно что делает бот.
Из гифки понятно что настраивается интеграция с гугл календарем и можно отражать что то в календаре через бота, время, деньги, теги. 
А можно подробнее, зачем это и что дальше делается с этой информацией.
На сколько я понял это для отражения\планирования работы на фрилансе?

**Comment by zhukovgreen** [comment]
вы правильо поняли. При помощи календаря и тагов модно автоматизировать репорт

**Comment by huxuxuya** [comment]
Спасибо, но все же не совсем понимаю полный сценарий использования.
Вы ведёте в календаре учёт плановых задач или фактических? 
Или календарь в качестве таск трекера используете?
И после того что то в календаре отразили как это используется, там же точное время не указывается и соответственно напоминалки не будет...

**Comment by zhukovgreen** [comment]
бот предполагает что события в календаре будут отражать ваше реальное время, проведенное над задачами. Он просто смотрит ваши события в календаре и если они помечены указанными тагами, то события собираютс в репорт.

Пример:
 Я планирую день с утра и создаю события. В конце дня я делаю корректировку. И так каждый день. В конце отчетного периода генерирую отчет.

**Comment by huxuxuya** [comment]
Теперь понял, спасибо :)
